CREATE TABLE Student(
	Id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name CHAR NOT NULL,
    Semester Int NOT NULL  
);

CREATE TABLE Teacher(
	Id Int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Email Varchar(255) NOT NULL,  
    Name CHAR NOT NULL 
);

CREATE TABLE Admin(
	Id int NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    Name CHAR NOT NULL
);
